### ISSUE TITLE
pass through the human-readable-description fields for all metadata

### ISSUE THREAD

**Issue by gregcaporaso** [caporaso-lab/mockrobiota#11]
and make them more descriptive (related to #10). 

@nbokulich, maybe you and I can do that together sometime soon?

**Comment by nbokulich** [comment]
I can do this today. Can you give me some details on minimum information you would like to include? Then I can go through and expand descriptions for each.

**Comment by gregcaporaso** [comment]
Just a couple of descriptive sentences of what it is, where it came from, and any relations to other data sets, for example:

A mock community composed of 15 bacteria represented in equal abundances in three replicate samples. These are the same community members present in mock-x, but in mock-x they are represented in uneven abundances. This was generated by Dr. XYZ at MIT in 2014.

**Comment by nbokulich** [comment]
Sounds good and thank you for the template sentence! I will complete these this afternoon.
