### ISSUE TITLE
add contributing guide

### ISSUE THREAD

**Issue by gregcaporaso** [caporaso-lab/mockrobiota#19]

**Comment by gregcaporaso** [comment]
The [example-1 README file](https://github.com/caporaso-lab/mockrobiota/blob/master/data/example-1/README.md) info should move to CONTRIBUTING.md - any objections @jairideout, @nbokulich? Seems like it will easily be forgotten, and then become outdated, where it is.

**Comment by nbokulich** [comment]
I agree

**Comment by jairideout** [comment]
👍
