### ISSUE TITLE
additional mock communities to include

### ISSUE THREAD

**Issue by gregcaporaso** [caporaso-lab/mockrobiota#26]
From Robert Edgar (via [feedback on the PeerJ pre-print](https://peerj.com/preprints/2065v1/#feedback-616)):
- [x] Kozich et al. "dual indexing" V4 HMP mock (doi: 10.1128/AEM.01043-13, FASTQ files: http://www.mothur.org/MiSeqDevelopmentData.html). This is yet another HMP V4 run, but is useful because it has a quite different error profile (presumably due to the different library preparation method).
- [x] The "Extreme" community used for DADA2 validation (doi:10.1038/nmeth.3869, SRA run id SRR2990088). This is useful because it has several species which are >97% similar so cannot be resolved by traditional OTU methods.

**Comment by nbokulich** [comment]
These datasets do not have barcode files. Should we change the travisCI requirements to eliminate the barcode file requirement?

**Comment by gregcaporaso** [comment]
> Should we change the travisCI requirements to eliminate the barcode file requirement?

Yes, I think so. Can we adapt the requirement in some way so there is either a barcodes file or some other scenario (I'm not able to download the files at the moment due to slow wifi connection, so I don't yet have a suggestion for what that requirement could be).

**Comment by nbokulich** [comment]
Thanks! perhaps we can require a valid barcodes fp if barcodes are listed in the mapping file, or if > 1 sample is listed in the mapping file.

**Comment by gregcaporaso** [comment]
That should work. Want to make that change? I can review tomorrow when I add the others to Dropbox.

**Comment by nbokulich** [comment]
Both of these communities (and others) were added with PR #52 . Resolving.
