### ISSUE TITLE
mock-8 raw data needs to be converted to fastq

### ISSUE THREAD

**Issue by gregcaporaso** [caporaso-lab/mockrobiota#28]
they're currently in single-line formats. 

@shiffer1 and @wmercurio are going to take a crack at this.

**Comment by shiffer1** [comment]
All barcode and sequence files have been reformatted and we have fastqs for everything but the mock10 rev seqs. That gzipped file is corrupted and we need a new one. As soon as that file is found the formatting can be updated. All the files are being held on the monsoon server at NAU under the control of @shiffer1.

**Comment by nbokulich** [comment]
The raw data have been updated to correct this issue, and new links are now available in `dataset-metadata.tsv`. Thank you, @shiffer1 for resolving this issue!
