### ISSUE TITLE
correct the precision in expected taxonomy files

### ISSUE THREAD

**Issue by gregcaporaso** [caporaso-lab/mockrobiota#3]
@nbokulich, when @jairideout and I were testing this we discovered that the relative abundances are off in some of the expected taxonomy files. We wanted to confirm that the taxa abundances in each sample sum to 1.0 (to seven decimal places, the `unitetest.assertFloatEqual` default). We found that in some cases they're not equal even to two decimal places. For example, in `mock-3`, the sum of the values in sample `HMPMockV1.2.Staggered1` is 1.02. Would you be able to look into this? We have a test file that you can run now which will help you identify these samples (run `python tests/check_data_integrity.py` in this repository - this is Python 3 only). 

Note that this issue is causing the current build to fail - I think it's important to have this block people from using the data for now.

**Comment by nbokulich** [comment]
sounds like this is an issue with the rounding... I will look into this.
Thanks for noticing!

Is this just an issue with greengenes, Silva, or both?

**Comment by gregcaporaso** [comment]
It's an issue with a bunch of them, to varying degrees. I'm realizing now that a table that sums the values for all dataset/database/version combinations would help. Either @jairideout or I can generate this for you today.

**Comment by jairideout** [comment]
Fixed in #9.
