### ISSUE TITLE
Mock-11 seems to be listed as B1 and bacterial data, It should be F2 and eukaryotic data

### ISSUE THREAD

**Issue by shiffer1** [caporaso-lab/mockrobiota#31]

**Comment by jairideout** [comment]
@shiffer1 was this a non-issue or did you close the issue by mistake?

**Comment by shiffer1** [comment]
It was a nonissue. I was thinking of mock 10.

**Comment by jairideout** [comment]
Ok thanks for confirming! I've accidentally closed issues in the past so wanted to make sure it was intentional :)
