### ISSUE TITLE
Mock 10 reverse reads gz is corrupted

### ISSUE THREAD

**Issue by shiffer1** [caporaso-lab/mockrobiota#33]
A direct download from the link provided for mock 10 reverse reads when gunzipped results in:
gunzip: SAG_rev.txt.gz: unexpected end of file
gunzip: SAG_rev.txt.gz: uncompress failed

It appears that the file is not complete.
Thanks,
Arron

**Comment by nbokulich** [comment]
It actually appears that this file is not gzipped at all. To see the true nature of this file:
less SAG_rev.txt.gz

However, this file contains far, far fewer sequences than the forward reads. I have not used the reverse reads from this mock community and got this file directly from the creator. I am following up with him now. If he does not have a replacement, we will delete this file.

**Comment by gregcaporaso** [comment]
Good plan.

**Comment by nbokulich** [comment]
So far, we have not found a replacement reverse read but the original contributors are hunting down a non-corrupted replacement. Until that occurs, we have removed the reverse read link and are closing this issue.
