### ISSUE TITLE
Shotgun Mock

### ISSUE THREAD

**Issue by davidvilanova** [caporaso-lab/mockrobiota#53]
Hi,
Just wondering if there are shotgun WGS mock communities (on Hiseq 2x150bp) ??

Thanks and great idea to have this repository.

**Comment by nbokulich** [comment]
Alas, we currently only have marker-gene sequencing datasets in mockrobiota, though we plan to host shotgun WGS metagenome datasets in the future and are actively searching for these. I will keep this issue open until that happens — at which point you will be notified via this issue request. In the mean time, if you use any mock metagenome datasets and would like to contribute these to mockrobiota, your help would be hugely appreciated!

**Comment by nbokulich** [comment]
@davidvilanova we now have our first shotgun metagenome mock community, [mock-17](https://github.com/caporaso-lab/mockrobiota/tree/master/data/mock-17). It is MiSeq, but perhaps still useful to you?

Note — I have not tested this mock community personally, but you can find more information on this mock community in the original publication, doi:10.1128/AEM.01043-13.
