### ISSUE TITLE
Potential issue demultiplexing mock-8

### ISSUE THREAD

**Issue by wasade** [caporaso-lab/mockrobiota#59]
I pulled down the forward read and barcode data for mock-8 and attempted to demultiplex it using QIIME2. For load into QIIME2, I'm saving the forward reads as `sequences.fastq.qz`, and specifying a semantic type of `EMPSingleEndSequences`. The resulting `.qza` file is approximately 5GB in size. 

If I do not reverse complement the sample barcodes (i.e., default use of `q2-demux`), the resulting `.qza` archive is approximately 6kb in size. If I reverse complement the barcodes in the sample metadata file, the resulting `.qza` is approximately 17MB in size. In the RC case, the samples come out with the following number of sequences:

- `Even1` : `127730`
- `Even2` : `87659`
- `Even3` : `111879`

The readme notes that reverse complement of the mapping file barcodes is necessary, and it does seem to yield more sequence, but the output is substantially smaller than I'd expect given the size of the raw data. I couldn't find expected numbers of sequences in the manuscript cited in the readme, are the above numbers inline with what is expected?

**Comment by nbokulich** [comment]
Yep, that matches what I have — thanks for checking!

The raw data contain many other non-mock samples for which barcode data are not provided, hence the great size reduction after demux.

**Comment by wasade** [comment]
Okay, thanks!
