### ISSUE TITLE
add raw-data-url for mock-11

### ISSUE THREAD

**Issue by jairideout** [caporaso-lab/mockrobiota#8]
@nbokulich we have an "NA" placeholder for now in `dataset-metadata.tsv` for mock-11, can you send us the raw data URL?

**Comment by nbokulich** [comment]
Found it:
ftp://ftp.microbio.me/pub/illumina-mock-communities-raw-data/L18S-1/

Thanks!
Nick

**Comment by jairideout** [comment]
Awesome, thanks!
