### ISSUE TITLE
Trouble generating a pull request

### ISSUE THREAD

**Issue by roey-angel** [caporaso-lab/mockrobiota#82]
I'm trying to submit two new mock communities, that passed the data integrity test.
I'm having trouble creating a pull request. I have some git experience but never created a pull request.
Trying to create a pull request on github it asks me to compare another branch to the master, but I'm stuck at that.
Could you provide more detailed instructions?

**Comment by nbokulich** [comment]
Hi @roey-angel ,
[These instructions](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md#submitting-code-to-scikit-bio) are for a different repository, but are a great outline for the steps that you should follow for submitting a pull request. It sounds like you have already done all of these steps and you are stuck at the last step, but basically you should:
1. Clone mockrobiota to make a personal fork (`roey-angel/mockrobiota`) and make a new topic branch in your local repo (`git checkout -b name-of-new-branch`)
2. Add all your new files in the appropriate directory structure in that branch (looks like your new mock communities would become `mock-27` and `mock-28`) and test
3. add/commit/push your changes (follow steps 8 and 10-12 in the document I linked to above) to push these changes to a branch of your repository clone (`roey-angel/mockrobiota`)
4. Submit a pull request to pull these changes into `mockrobiota/master` (once you open up Github and go to `roey-angel/mockrobiota` you will see a notification/option to submit a PR). The correct paths should show up by default, but just make sure that the base repo/branch (that you are pulling into) will be `caporaso-lab/mockrobiota:master`, and the "compare" repo that you should be pulling from will be `roey-angel/mockrobiota:name-of-new-branch`.

Let me know if that helps or if there is a particular stage that needs more clarity. Thanks!

**Comment by roey-angel** [comment]
Thanks!
I think I managed to get everything right.
One thing I miss is the greengenes taxonomy. The taxonomy I added under source is based on Silva. I've never worked with greengenes so I'm not sure how to add that  info and the website seems to be temporarily down. Moreover, while we use this mock community for MiSeq runs we validated the sequences using Sanger (so there's no OTU clustering).

**Comment by nbokulich** [comment]
Thanks @roey-angel ! I am really looking forward to getting these mock communities in mockrobiota.

I reviewed your files and there are a few changes to make (most importantly, we need links to the raw MiSeq data). We can continue correspondence on the PR discussion page.

Do not worry about Silva/greengenes (those are 16S-specific). See my review comments in the PR discussion for more details...
