### ISSUE TITLE
Missing MOCK data

### ISSUE THREAD

**Issue by Subc0mandante** [caporaso-lab/mockrobiota#94]
Dear authors, 

Thank you for the great work you have done on the Qiime project... But may I ask you about the source data of your MOCK experiments? 

I don't see them in any of the Mock folders... Thank you 

Karel

**Comment by nbokulich** [comment]
Thanks Karel!
please see the dataset metadata file associated with each dataset. This contains the DOI information and other relevant information.

**Comment by Subc0mandante** [comment]
Hey Nick,

thank you for your reply... I was expecting the raw data in the directory :) Thank you anyway
